version: "3.9"  # optional since v1.27.0
services:
  #============= POSTGRES DB ==========
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=postgres
  #============= LastPick =============
  lastpick:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - 'db'
    environment:
      - datasource_url=jdbc:postgresql://db:5432/postgres
      - datasource_username=postgres
      - datasource_password=pass123
